import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--headless=new'] })
const p = await b.newPage({ viewport: { width: 1400, height: 1000 } })
await p.goto('http://localhost:4173/?view=backtesting', { waitUntil: 'networkidle' })
await p.waitForTimeout(1200)
await p.locator('input[type="file"]').first().setInputFiles('/tmp/eurusd.csv'); await p.waitForTimeout(1500)
await p.locator('button', { hasText: /Place order/i }).first().click(); await p.waitForTimeout(300)
const nextBtn = () => p.locator('button', { hasText: /^›$|Next|Step/ }).first()
for (let i=0;i<12;i++){ await nextBtn().click(); await p.waitForTimeout(30) }
const close = p.locator('button', { hasText: /^Close$/i }).first()
console.log('close buttons:', await p.locator('button', { hasText: /^Close$/i }).count())
await close.scrollIntoViewIfNeeded(); await close.click(); await p.waitForTimeout(500)
console.log('textContent has phrase:', await p.evaluate(()=>document.body.textContent.includes('Where the money went')))
console.log('innerText has phrase:', await p.evaluate(()=>document.body.innerText.includes('Where the money went')))
const t = await p.evaluate(()=>document.body.textContent)
const r = t.indexOf('No closed trades')
console.log('empty-state present:', r >= 0)
const q = t.indexOf('Results')
console.log(t.slice(q, q+300))
await b.close()
