import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--headless=new'] })
const ctx = await b.newContext({ viewport: { width: 1280, height: 1000 }, acceptDownloads: true })
const p = await ctx.newPage()
const errs = []; p.on('pageerror', e => errs.push(String(e)))
p.on('console', m => m.type()==='error' && !/ERR_CONNECTION/.test(m.text()) && errs.push(m.text()))
await p.goto('http://localhost:4173/?view=settings&tab=preferences', { waitUntil: 'networkidle' })
await p.evaluate(() => localStorage.setItem('forex_greek_trades', JSON.stringify(
  Array.from({length:5},(_,i)=>({id:'t'+i,symbol:'EURUSD',side:'Long',pnl:100,fees:0,traded_at:new Date().toISOString()})))))
await p.reload({ waitUntil: 'networkidle' }); await p.waitForTimeout(1200)
const txt = await p.evaluate(()=>document.body.textContent)
const j = txt.indexOf('Your Data')
console.log('PANEL:\n' + (j<0?'[MISSING]':txt.slice(j, j+620)))
// export
const dl = p.waitForEvent('download', { timeout: 15000 }).catch(()=>null)
const btn = p.locator('button', { hasText: 'Download my data' }).first()
await btn.scrollIntoViewIfNeeded(); await btn.click()
const d = await dl
console.log('DOWNLOAD:', d ? d.suggestedFilename() : 'none')
await p.waitForTimeout(800)
const t2 = await p.evaluate(()=>document.body.textContent)
const k = t2.indexOf('Downloaded. It contains')
console.log('SUMMARY:\n' + (k<0?'[MISSING]':t2.slice(k, k+400)))
// confirmation gating
const del = p.locator('button', { hasText: /^Delete account$/ }).first()
await del.scrollIntoViewIfNeeded(); await del.click(); await p.waitForTimeout(500)
const confirmBtn = p.locator('button', { hasText: /^Confirm$/ }).first()
console.log('confirm disabled with empty input:', !(await confirmBtn.isEnabled()))
const inp = p.locator('input[placeholder="DELETE MY ACCOUNT"]').first()
await inp.fill('DELETE'); await p.waitForTimeout(300)
console.log('confirm disabled with wrong phrase:', !(await confirmBtn.isEnabled()))
await inp.fill('delete my account'); await p.waitForTimeout(300)
console.log('confirm enabled with right phrase (any case):', await confirmBtn.isEnabled())
console.log('OVERFLOW:', await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth))
await p.setViewportSize({width:390,height:800}); await p.waitForTimeout(500)
console.log('MOBILE OVERFLOW:', await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth))
console.log('ERRORS:', errs.slice(0,2))
await b.close()
