import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--headless=new'] })
const p = await b.newPage({ viewport: { width: 1280, height: 1000 } })
const errs = []; p.on('pageerror', e => errs.push(String(e)))
p.on('console', m => m.type()==='error' && !/ERR_CONNECTION/.test(m.text()) && errs.push(m.text()))
await p.goto('http://localhost:4173/?view=settings&tab=billing', { waitUntil: 'networkidle' })
await p.waitForTimeout(1600)
const txt = await p.evaluate(()=>document.body.textContent)
const j = txt.indexOf('Plans')
console.log(j<0 ? '[MISSING]' : txt.slice(j, j+780))
console.log('---')
console.log('upgrade buttons:', await p.locator('button', { hasText: /^Upgrade to/ }).count())
console.log('manage billing shown:', await p.locator('button', { hasText: 'Manage billing' }).count())
console.log('OVERFLOW:', await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth))
await p.setViewportSize({width:390,height:800}); await p.waitForTimeout(600)
console.log('MOBILE OVERFLOW:', await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth))
console.log('ERRORS:', errs.slice(0,2))
await b.close()
